---
- name: Basic MySQL Server Health Check
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "10.112.0.11"
    mysql_port: 3306

  tasks:
    - name: Check if MySQL server is reachable (TCP connection)
      wait_for:
        host: "{{ mysql_host }}"
        port: "{{ mysql_port }}"
        timeout: 5
        state: started
      register: mysql_connection
      ignore_errors: yes

    - name: Display MySQL connectivity status
      debug:
        msg: |
          🔍 MySQL Server Connectivity Check:
          
          {% if mysql_connection is succeeded %}
          ✅ MySQL server at {{ mysql_host }}:{{ mysql_port }} is REACHABLE
          
          This means the server is:
           - Running and accepting connections
           - Not blocked by firewalls
           - Network route is available
          
          For more detailed health information, you will need:
           - MySQL client installed on this machine
           - Proper credentials with sufficient privileges
           - Additional configuration may be required
          {% else %}
          ❌ MySQL server at {{ mysql_host }}:{{ mysql_port }} is UNREACHABLE
          
          Possible reasons:
           - MySQL service is not running
           - Server is down or restarting
           - Port 3306 is blocked by firewall
           - Network connectivity issues
           - Wrong IP address or port
          
          Recommended actions:
           - Verify MySQL is running on the server
           - Check firewall settings
           - Confirm network connectivity
           - Verify host and port configuration
          {% endif %}
