---
- name: Check MySQL Server Health
  hosts: localhost
  gather_facts: yes  # Enable fact gathering
  vars:
    mysql_host: "{{ mysql_host }}"
    mysql_user: "{{ mysql_user }}"
    mysql_password: "{{ mysql_password }}"

  tasks:
    - name: Ensure mysql-client or mariadb-client is installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-client
        - mariadb-client
        - mysql
        - mariadb
      ignore_errors: yes
      become: yes

    # Proceed with MySQL health checks...
