---
- name: Connect to Linux MySQL Server and Perform Health Checks via SSH
  hosts: all
  become: true
  vars:
    mysql_user: "mysqlAutomation"
    mysql_password: "mysqlAutomation"
    mysql_host: "127.0.0.1"
    ssh_user: "your_ssh_username"  # Replace with your SSH username

  tasks:

    - name: Check DB space utilization via SSH
      shell: |
        ssh {{ ssh_user }}@{{ mysql_host }} "mysql -u'{{ mysql_user }}' -p'{{ mysql_password }}' -e \"
        SELECT table_schema AS 'Database', 
               ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS 'Size (MB)' 
        FROM information_schema.tables 
        GROUP BY table_schema;\""
      register: db_space_output
      no_log: true

    - name: Show DB space utilization
      debug:
        msg: "{{ db_space_output.stdout_lines }}"

    - name: Check health of DB via SSH (Threads Connected)
      shell: |
        ssh {{ ssh_user }}@{{ mysql_host }} "mysql -u'{{ mysql_user }}' -p'{{ mysql_password }}' -e \"
        SHOW GLOBAL STATUS LIKE 'Threads_connected';\""
      register: db_health_status
      changed_when: false
      no_log: true

    - name: Show DB health status
      debug:
        msg: "DB Health Status: {{ db_health_status.stdout_lines }}"

    - name: Check for deadlocks in MySQL InnoDB engine via SSH
      shell: |
        ssh {{ ssh_user }}@{{ mysql_host }} "mysql -u'{{ mysql_user }}' -p'{{ mysql_password }}' -e \"
        SHOW ENGINE INNODB STATUS\\G\""
      register: innodb_status
      changed_when: false
      no_log: true

    - name: Show InnoDB status for deadlocks
      debug:
        msg: "InnoDB Status (Deadlocks): {{ innodb_status.stdout_lines }}"

    - name: Check for job activities in MySQL via SSH
      shell: |
        ssh {{ ssh_user }}@{{ mysql_host }} "mysql -u'{{ mysql_user }}' -p'{{ mysql_password }}' -e \"
        SHOW PROCESSLIST;\""
      register: job_activity
      changed_when: false
      no_log: true

    - name: Show running job activities in MySQL
      debug:
        msg: "Current MySQL job activities: {{ job_activity.stdout_lines }}"
