- name: MySQL Server Health Check
  hosts: mysql_servers
  become: yes
  gather_facts: no

  tasks:
    # 1️⃣ Connect to MySQL Server
    - name: Check MySQL Connection
      community.mysql.mysql_query:
        login_host: "localhost"
        login_user: "root"
        login_password: "your_password"
        query: "SELECT VERSION();"
      register: mysql_version

    - name: Display MySQL Version
      debug:
        var: mysql_version
