---
- name: Check MySQL Server Health
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "10.112.0.11"
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_port: 3306
    mysql_cli_options: "-h{{ mysql_host }} -P{{ mysql_port }} -u{{ mysql_user }} --password={{ mysql_password }}"

  tasks:
    - name: Test MySQL Connection
      command: >
        mysql {{ mysql_cli_options }} -e "SELECT 'Connection successful' AS Status;"
      register: connection_test
      failed_when: connection_test.rc != 0
      changed_when: false

    - name: Debug Connection Test
      debug:
        var: connection_test
      when: connection_test is defined

    - name: Ensure MySQL User Has Permissions
      command: >
        mysql {{ mysql_cli_options }} -e "
        GRANT ALL PRIVILEGES ON *.* TO '{{ mysql_user }}'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;"
      register: grant_result
      failed_when: grant_result.rc != 0
      changed_when: false
      when: connection_test is succeeded

    - name: Get Database Space Utilization
      command: >
        mysql {{ mysql_cli_options }} -N -e "
        SELECT table_schema, 
        ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS SizeMB 
        FROM information_schema.tables 
        GROUP BY table_schema;"
      register: db_space
      failed_when: db_space.rc != 0
      changed_when: false
      when: connection_test is succeeded

    - name: Get Database Health
      command: >
        mysql {{ mysql_cli_options }} -N -e "
        SELECT schema_name AS database_name, 'ONLINE' AS status, 
        (SELECT COUNT(*) FROM information_schema.processlist WHERE command != 'Sleep') AS active_requests,
        (SELECT COUNT(*) FROM information_schema.processlist) AS active_connections,
        (SELECT COUNT(*) FROM information_schema.processlist WHERE state = 'Waiting for table metadata lock') AS pending_requests,
        (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_running') AS running_threads
        FROM information_schema.schemata;"
      register: db_health
      failed_when: db_health.rc != 0
      changed_when: false
      when: connection_test is succeeded

    - name: Check for Deadlocks
      command: >
        mysql {{ mysql_cli_options }} -N -e "
        SELECT COUNT(*) AS deadlocks 
        FROM information_schema.innodb_trx t1 
        INNER JOIN information_schema.innodb_trx t2 
        WHERE t1.trx_id != t2.trx_id 
        AND t1.trx_waiting_lock_id = t2.trx_lock_id 
        AND t2.trx_waiting_lock_id = t1.trx_lock_id;"
      register: deadlocks
      failed_when: deadlocks.rc != 0
      changed_when: false
      when: connection_test is succeeded

    - name: Get MySQL Events Status
      command: >
        mysql {{ mysql_cli_options }} -N -e "
        SELECT event_name, status, last_executed,
        CASE 
          WHEN execute_at IS NOT NULL THEN 'SCHEDULED'
          WHEN on_completion = 'PRESERVE' THEN 'RECURRING'
          ELSE 'ONE-TIME'
        END as event_type
        FROM information_schema.events;"
      register: event_activities
      failed_when: event_activities.rc != 0
      changed_when: false
      when: connection_test is succeeded

    - name: Process MySQL Output
      set_fact:
        db_space_fact: "{{ db_space.stdout_lines | default([]) | map('split', '\t') | list }}"
        db_health_fact: "{{ db_health.stdout_lines | default([]) | map('split', '\t') | list }}"
        deadlocks_fact: "{{ deadlocks.stdout | default('0') | trim }}"
        event_activities_fact: "{{ event_activities.stdout_lines | default([]) | map('split', '\t') | list }}"
      when: connection_test is succeeded

    - name: Display Formatted Results
      debug:
        msg: |
          {% if connection_test is failed %}
          ❌ MySQL Connection Failed: Unable to connect to MySQL server. Please check credentials and server status.
          {% else %}
          📊 Database Space Utilization:
          {% if db_space_fact | length > 0 %}
          {% for item in db_space_fact %}
           - {{ item[0] }}: {{ item[1] }} MB
          {% endfor %}
          {% else %}
           - No database space data available
          {% endif %}
          
          🚨 Deadlocks:
          {% if deadlocks_fact | int > 0 %}
           - {{ deadlocks_fact }} deadlocks detected!
          {% else %}
           - No deadlocks detected
          {% endif %}
          
          [ℹ️] Events query returned {{ event_activities_fact | length }} rows.
          
          🛠 MySQL Events Status:
          {% if event_activities_fact | length > 0 %}
          {% for event in event_activities_fact %}
           - Event: {{ event[0] }}
             Status: {{ event[1] }}
             Last Executed: {{ event[2] }}
             Type: {{ event[3] }}
          {% endfor %}
          {% else %}
           - No events data available
          {% endif %}
          
          🩺 Database Health Check:
          {% if db_health_fact | length > 0 %}
          {% for item in db_health_fact %}
           - Database: {{ item[0] }}
             - Status: {{ item[1] }}
             - Active Requests: {{ item[2] }}
             - Active User Connections: {{ item[3] }}
             - Pending Requests: {{ item[4] }}
             - Running Threads: {{ item[5] }}
          {% endfor %}
          {% else %}
           - No database health data available
          {% endif %}
          {% endif %}
